apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: postgres-airflow
  name: postgres-airflow
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: postgres-airflow
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: postgres-airflow
    spec:
      restartPolicy: Always
      containers:
        - name: postgres
          image: postgres
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
              protocol: TCP
             
          env:
            - name: POSTGRES_USER
              value: root

            - name: POSTGRES_PASSWORD
              value: root

            - name: POSTGRES_DB
              value: airflow

---

kind: Service
apiVersion: v1
metadata:
  labels:
    run: postgres-airflow
  name: postgres-airflow-service
spec:
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    run: postgres-airflow
