apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-scheduler
  labels:
    app: airflow-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-scheduler
  template:
    metadata:
      labels:
        app: airflow-scheduler
    spec:
      containers:
        - name: scheduler
          image: airflow:latest
          imagePullPolicy: IfNotPresent
          args: ["scheduler"]
          env:
            - name: AIRFLOW__KUBERNETES__NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace

            - name: SQL_ALCHEMY_CONN
              valueFrom:
                secretKeyRef:
                  name: airflow-secrets
                  key: sql_alchemy_conn

          volumeMounts:
            - name: airflow-configmap
              mountPath: /root/airflow/airflow.cfg
              subPath: airflow.cfg

            - name: airflow-dags
              mountPath: /root/airflow/dags

            - name: airflow-logs
              mountPath: /root/airflow/logs

            - name: airflow-plugins
              mountPath: /root/airflow/plugins

      volumes:
        - name: airflow-configmap
          configMap:
            name: airflow-configmap

        - name: airflow-logs
          hostPath:
            path: { { LOGS_VOLUMES } }

        - name: airflow-dags
          hostPath:
            path: { { DAGS_VOLUMES } }

        - name: airflow-plugins
          hostPath:
            path: { { PLUGINS_VOLUMES } }
